package com.api.ejemplo.apidocker.model;

//import lombok.Data;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
//import java.util.Date;



@DynamoDBTable(tableName = "Fondos")
public class Fondo {

    private String fondoId;
    private String nombreFondo;
    private String descripcion;
    private double montoMinimo; // Este campo podría ser parte de los fondos suscritos si necesitas llevar un registro específico

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "fondoId")
    public String getFondoId() {
        return fondoId;
    }

    public void setFondoId(String fondoId) {
        this.fondoId = fondoId;
    }

    @DynamoDBAttribute(attributeName = "nombreFondo")
    public String getNombreFondo() {
        return nombreFondo;
    }

    public void setNombreFondo(String nombreFondo) {
        this.nombreFondo = nombreFondo;
    }

    @DynamoDBAttribute(attributeName = "descripcion")
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @DynamoDBAttribute(attributeName = "montoMinimo")
    public double getMontoMinimo() {
        return montoMinimo;
    }

    public void setMontoMinimo(double montoMinimo) {
        this.montoMinimo = montoMinimo;
    }

    // Otros atributos y métodos según sea necesario
}
